/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ua.khpi.pinecone.sequence;

import java.util.List;

import static ua.khpi.pinecone.polynomial.form.InitPanel.initPanel;
//import static ua.khpi.pinecone.polynomial.form.InitPanel.resultSSequenceForm;
import static ua.khpi.pinecone.polynomial.form.InitPanel.sequenceForm;

/**
 *
 * @author inc_f
 */
public class SequenceForm extends javax.swing.JFrame {

//    private ReportEntity reportEntity;

    /**
     * Creates new form SequenceForm
     */
    public SequenceForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        outSequence = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        sequenceLoadFile = new javax.swing.JButton();
        sequenceBlockForms = new javax.swing.JButton();
        sequenceNext = new javax.swing.JButton();
        sequencePrev = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        outSequence.setEditable(false);
        outSequence.setColumns(20);
        outSequence.setRows(5);
        jScrollPane1.setViewportView(outSequence);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Set sequence ");

        sequenceLoadFile.setText("File load");
        sequenceLoadFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sequenceLoadFileMouseClicked(evt);
            }
        });

        sequenceBlockForms.setText("<block forms>");
        sequenceBlockForms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sequenceBlockFormsMouseClicked(evt);
            }
        });

        sequenceNext.setText("NEXT");
        sequenceNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sequenceNextMouseClicked(evt);
            }
        });

        sequencePrev.setText("PREV");
        sequencePrev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sequencePrevMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sequenceLoadFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sequenceBlockForms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(sequencePrev, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sequenceNext)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sequenceLoadFile, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sequenceBlockForms, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sequenceNext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sequencePrev, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sequenceLoadFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sequenceLoadFileMouseClicked
        sequence = new SSequence();
        StringBuilder stringBuilder = new StringBuilder();
        List<List<Integer>> lists = sequence.getSequence();
        for (List<Integer> list : lists) {
            for (Integer integer : list) {
                stringBuilder.append(integer).append(" ");
            }
            stringBuilder.append(System.lineSeparator());
        }
        outSequence.setText(stringBuilder.toString());
    }//GEN-LAST:event_sequenceLoadFileMouseClicked

    private void sequenceBlockFormsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sequenceBlockFormsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sequenceBlockFormsMouseClicked

    private void sequencePrevMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sequencePrevMouseClicked
        initPanel.setVisible(true);
        sequenceForm.setVisible(false);
    }//GEN-LAST:event_sequencePrevMouseClicked

    private void sequenceNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sequenceNextMouseClicked
//        resultSSequenceForm.setVisible(true);
        sequenceForm.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_sequenceNextMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea outSequence;
    private javax.swing.JButton sequenceBlockForms;
    private javax.swing.JButton sequenceLoadFile;
    private javax.swing.JButton sequenceNext;
    private javax.swing.JButton sequencePrev;
    // End of variables declaration//GEN-END:variables

    private SSequence sequence;
}
